version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - npm install
  - npm add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - npm run release

test: off